# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a3aef254134a790f2b85ab74a251a0539c66c794196f37c5dd722e3b90a98302699ce3bb1d40949d96ddb9a9c5e5db1b3aec79842a19ae4c256143a667c4cf4

test:
  secret_key_base: 7b61bcab34de0795bd70776292115f042bed9e8899028ec32e754330afb00aed0c9fba18db45bc17b9e44ec1d36cf7835dfdc8b52df57e96764ffd60a80a3bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
